### ISSUE TITLE
Submitting a JOSS paper

### ISSUE THREAD

**Issue by dfm** [dfm/emcee#316]
I've just pushed a draft of a paper for submission to [JOSS](https://joss.theoj.org) in parallel with the release of version 3.0. I'd like to invite members of the community to join as an author on this paper if you're are interested. Please reply to this thread with your full name, affiliation, and (optionally) ORCID in [the format needed by JOSS](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) if you would like to join as an author. Pull requests or comments about the manuscript are also welcome! For example, my info is:

```
name: Daniel Foreman-Mackey
orcid: 0000-0003-0872-7098
affiliation: Center for Computational Astrophysics, Flatiron Institute
```

I'd like to submit this on 28 Oct 2019 so let me know if you're interested in joining, but need more time to decide.

Pinging committers with at least 10 lines (but others are also welcome if you feel that you have contributed!):

- @farr 
- @manodeep 
- @davidwhogg 
- @jeremysanders 
- @eteq 
- @joezuntz 
- @pkgw 
- @andyfaff 
- @bencebeky 
- @dstndstn 
- @drphilmarshall 
- @willvousden 
- @terhardt 
- @Christopher-Bradshaw 
- @ipashchenko 
- @OriolAbril 
- @ericdill 
- @mindriot101 
- @nkern 
- @migueldvb

**Comment by manodeep** [comment]
@dfm Thanks! Yes, I would like to be listed as an author on the paper. 

```
name: Manodeep Sinha
orcid: 0000-0002-4845-1228
affiliation: "1, 2" 

affiliations:
 - name: Centre for Astrophysics & Supercomputing, Swinburne University of Technology
   index: 1
 - name: ARC Centre of Excellence for All Sky Astrophysics in 3 Dimensions (ASTRO 3D)
   index: 2
```

**Comment by andyfaff** [comment]
That's a very kind invitation, I would like to accept.

```
name: Andrew R. J. Nelson
orcid: 0000-0002-4548-3558
affiliation: "1" 

affiliations:
 - name: Australian Nuclear Science and Technology Organisation, NSW, Australia
   index: 1
```

**Comment by terhardt** [comment]
Thank you for the kind invitation and for drafting the paper. I'd feel honoured to accept.

    name: Tobias Erhardt
    orcid: 0000-0002-6683-6746
    affiliation: Climate and Environmental Physics and Oeschger Center for Climate Change Research, University of Bern, Bern, Switzerland

**Comment by joezuntz** [comment]
This is very kind of you, thank you very much.  If you're happy to include me I'd be happy to accept.

```
name: Joe Zuntz
orcid: 0000-0001-9789-9646
affiliation: Institute for Astronomy, University of Edinburgh, Edinburgh, EH9 3HJ, UK
```

**Comment by ipashchenko** [comment]
Thank you, Dan. I would like to accept your kind invitation.

name: Ilya Pashchenko
orcid: 0000-0002-9404-7023
affiliation: P.N. Lebedev Physical Institute of the Russian Academy of Sciences, Moscow, Russia

**Comment by pkgw** [comment]
Thanks for the invitation!

```
  - name: Peter K. G. Williams
    orcid: 0000-0003-3734-3587
    affiliation: "1, 2"
```

```
affiliations:
 - name: "Center for Astrophysics | Harvard & Smithsonian"
   index: 1
 - name: American Astronomical Society
   index: 2
```
